config/routes.rb
Rails.application.routes.draw do
  root to: 'books#index'

  resources :books, only: [:new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  VIM = 2_978_247 # character count war and peace

  mount_uploader :attached_file, BookUploader

  def self.txt_size(file)
    file = File.open(file,'r')
    size = file.read.squish.size
    file.close
    size
  end

  def self.epub_size(file)
    arr = Array.new
    book = EPUB::Parser.parse(file)
    book.each_page_on_spine do |page|
      arr << page.read
    end
    arr.join(' ').gsub(/<\/[^>]*>/, ' ').gsub(/<[^>]*>/, '').squish.size
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.order(created_at: :desc)
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(page_params)

    if @book.save
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to root_path
  end

  private

  def page_params
    params.require(:book).permit(:title, :author, :attached_file)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def vim(characters_count)
    (characters_count.to_f / Book::VIM).round(2)
  end
end

app/views/books/_book.html.erb
<tr>
  <td><%= book_counter + 1 %></td>
  <td class="left"><%= book.author %></td>
  <td class="left"><%= book.title %></td>
  <td><%= number_with_delimiter(book.length, delimiter: ' ') %></td>
  <td><%= vim(book.length) %></td>
</tr>

app/views/books/index.html.erb
<div class="content_wrapper">
  <div class="header_wrapper">
    <div class="page_header">
      <h1>Books</h1>
      <div class="create_button"><%= link_to 'Добавить книгу +', new_book_path %></div>
    </div>
  </div>
  <div class="page_wrapper">
    <div class="page_content">
      <div class="table_wrapper">
        <table cellspacing="0" cellpadding="0">
          <thead>
            <tr>
              <td>#</td>
              <td class="left">Автор</td>
              <td class="left">Название</td>
              <td>Объем</td>
              <td>ВиМ</td>
            </tr>
          </thead>
          <tbody>
            <%= render @books %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/books/new.html.erb
<div class="content_wrapper">
  <div class="header_wrapper">
    <div class="page_header">
      <h1>Новая книга</h1>
    </div>
  </div>
  <div class="page_wrapper">
    <div class="page_content">
      <div class="form_wrapper">
        <% if @book.errors.any? %>
          <div class="error_explanation">
            <i class="material-icons">error_outline</i>
            <h2>Ошибки:</h2>
            <ul>
              <% @book.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <%= form_for @book do |f| %>
          <div class="form_item">
            <div class="label_item"><%= f.label :title %></div>
            <div class="input_item"><%= f.text_field :title %></div>
          </div>
          <div class="form_item">
            <div class="label_item"><%= f.label :author %></div>
            <div class="input_item"><%= f.text_field :author %></div>
          </div>
          <div class="form_item">
            <div class="label_item"><%= f.label :attached_file %></div>
            <div class="input_item"><%= f.file_field :attached_file %></div>
          </div>
          <div class="form_item actions">
            <div class="input_item"><%= f.submit %></div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Mybooks</title>
    <meta name="viewport" content="user-scalable=no, initial-scale=1, maximum-scale=1, minimum-scale=1, width=device-width, height=device-height, target-densitydpi=device-dpi, user-scalable=no" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,400italic">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div id="wrapper">
      <div class="page-container">
        <div id='content'><%= yield %></div>
      </div>
    </div>
  </body>
</html>